STATUT = [
    ('CLIENT','CLIENT'),
    ('EMPLOYE','EMPLOYE'),
    ('FOURNISSEUR','FOURNISSEUR'),
    ('ASSOCIE','ASSOCIE'),
    ('CITOYEN','CITOYEN'),
]

CATEGORY = [
    ('SERVICE CLIENT','SERVICE CLIENT'),
    ('SERVICE CLIENT','SERVICE CLIENT'),
    ('SERVICE CLIENT','SERVICE CLIENT'),
    ('SERVICE CLIENT','SERVICE CLIENT'),
]