STATUT = [
    ('CLIENT','CLIENT'),
    ('CITOYEN','CITOYEN'),
]

CATEGORY = [
    ('SERVICE CLIENT','SERVICE CLIENT'),
    ('SERVICE CLIENT','SERVICE CLIENT'),
    ('SERVICE CLIENT','SERVICE CLIENT'),
    ('SERVICE CLIENT','SERVICE CLIENT'),
]


STATUT_COM = [
    ('TRAITEE','TRAITEE'),
    ("EN COURS","EN COURS"),
    ("REJETEE","REJETEE"),
]